### ISSUE TITLE
No executable

### ISSUE THREAD

**Issue by Vault911** [rquinio/PortraitBuilder#12]
I haven't found any executables in the archive. Am I missing something?

**Comment by rquinio** [comment]
Currently the executables are attached in the [CK2 modding forum thread](https://forum.paradoxplaza.com/forum/index.php?threads/utility-portrait-builder-v2.941117/), in order to provide support in a single place.

**Comment by rquinio** [comment]
I've now also mirrored the executables (as zip) on https://github.com/rquinio/PortraitBuilder/releases
